name: Publish Docker image (amd64)

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      name:
        description: 'reason'
        required: false

jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check if tags exist
        id: check_tags
        run: |
          if git describe --tags > /dev/null 2>&1; then
            echo "tags_exist=true" >> $GITHUB_ENV
          else
            echo "tags_exist=false" >> $GITHUB_ENV
          fi
      
      - name: Save version info
        if: env.tags_exist == 'true'
        run: git describe --tags > VERSION
      
      - name: Save fallback version info
        if: env.tags_exist == 'false'
        run: echo "no-tag-$(git rev-parse --short HEAD)" > VERSION

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ag471782517/new-api

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
