name: Build and Push Docker images

on:
  push:
    tags:
      - '*'
      - '!*-alpha'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Display build version and date
        run: |
          echo "Version tag: ${{ github.ref_name }}"
          echo "Date tag: $(date +'%m.%d')"
          echo "DATE_TAG=$(date +'%m.%d')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: username/repository
          # 根据触发类型设置标签
          tags: |
            type=ref,event=push
            type=raw,value=$(date +'%m.%d'),enable={{ github.event_name == 'workflow_dispatch' }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
